//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skade.CrossCutting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserInterfaceRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserInterfaceRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Skade.CrossCutting.Resources.UserInterfaceRes", typeof(UserInterfaceRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Command_Cancel_Caption {
            get {
                return ResourceManager.GetString("Command_Cancel_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Command_Create_Caption {
            get {
                return ResourceManager.GetString("Command_Create_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Command_OK_Caption {
            get {
                return ResourceManager.GetString("Command_OK_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Command_Search_Caption {
            get {
                return ResourceManager.GetString("Command_Search_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °.
        /// </summary>
        public static string General_Degree_Symbol {
            get {
                return ResourceManager.GetString("General_Degree_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string General_Description {
            get {
                return ResourceManager.GetString("General_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string General_Error {
            get {
                return ResourceManager.GetString("General_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string General_Information {
            get {
                return ResourceManager.GetString("General_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        public static string General_KilometersPerHour_Short {
            get {
                return ResourceManager.GetString("General_KilometersPerHour_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude/Longitude.
        /// </summary>
        public static string General_Latitude_Longitude {
            get {
                return ResourceManager.GetString("General_Latitude_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string General_Meter_Short {
            get {
                return ResourceManager.GetString("General_Meter_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m/s.
        /// </summary>
        public static string General_MetersPerSecond_Short {
            get {
                return ResourceManager.GetString("General_MetersPerSecond_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mph.
        /// </summary>
        public static string General_MilesPerHour_Short {
            get {
                return ResourceManager.GetString("General_MilesPerHour_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string General_Name {
            get {
                return ResourceManager.GetString("General_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string General_No {
            get {
                return ResourceManager.GetString("General_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string General_NotApplicable_Short {
            get {
                return ResourceManager.GetString("General_NotApplicable_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected.
        /// </summary>
        public static string General_NotConnected {
            get {
                return ResourceManager.GetString("General_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string General_Paste {
            get {
                return ResourceManager.GetString("General_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to px.
        /// </summary>
        public static string General_Pixel_Short {
            get {
                return ResourceManager.GetString("General_Pixel_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string General_Project {
            get {
                return ResourceManager.GetString("General_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Not Loaded.
        /// </summary>
        public static string General_Project_NotLoaded {
            get {
                return ResourceManager.GetString("General_Project_NotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string General_Unknown {
            get {
                return ResourceManager.GetString("General_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string General_Yes {
            get {
                return ResourceManager.GetString("General_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        public static string Language_Chinese {
            get {
                return ResourceManager.GetString("Language_Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (British).
        /// </summary>
        public static string Language_English_British {
            get {
                return ResourceManager.GetString("Language_English_British", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string Language_French {
            get {
                return ResourceManager.GetString("Language_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string Language_German {
            get {
                return ResourceManager.GetString("Language_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string Language_Japanese {
            get {
                return ResourceManager.GetString("Language_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string Language_Russian {
            get {
                return ResourceManager.GetString("Language_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Language_Spanish {
            get {
                return ResourceManager.GetString("Language_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish.
        /// </summary>
        public static string Language_Swedish {
            get {
                return ResourceManager.GetString("Language_Swedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Changed.
        /// </summary>
        public static string Msg_LanguageChanged {
            get {
                return ResourceManager.GetString("Msg_LanguageChanged", resourceCulture);
            }
        }
    }
}
